[package]
name = "benchmark-client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.58", features = ["derive"] }
mio = { version = "1", features = ["os-poll", "net"] }
quiche = "0.25.0"
ring = "0.17"
url = "2"
